# Generated by Django 5.0.6 on 2024-06-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='booking.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.administrator')),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.availabletime')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.client')),
            ],
        ),
    ]
