# Generated by Django 5.1 on 2024-09-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='amount',
        ),
    ]
